# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  database: coincoin
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: development_coincoin

test:
  <<: *default
  database: test_db_coincoin

production:
  <<: *default
  database: production_coincoin